// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "SaveAsDialog.H"

inline void SaveAsDialog::cb_Ok_i(Fl_Return_Button* o, void*) {
  m_ok = true;
o->window()->hide();
}
void SaveAsDialog::cb_Ok(Fl_Return_Button* o, void* v) {
  ((SaveAsDialog*)(o->parent()->user_data()))->cb_Ok_i(o,v);
}

inline void SaveAsDialog::cb_Cancel_i(Fl_Button* o, void*) {
  o->window()->hide();
}
void SaveAsDialog::cb_Cancel(Fl_Button* o, void* v) {
  ((SaveAsDialog*)(o->parent()->user_data()))->cb_Cancel_i(o,v);
}

SaveAsDialog::SaveAsDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = saveAsDialog = new Fl_Double_Window(335, 135, "Save as Dialog");
    w = o;
    o->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(0, 0, 335, 40, "Save Project as");
      o->labelfont(1);
      o->labelsize(16);
    }
    project_name = new Fl_Input(110, 55, 215, 25, "Project Name");
    { Fl_Return_Button* o = new Fl_Return_Button(175, 100, 150, 25, "Ok");
      o->callback((Fl_Callback*)cb_Ok);
      w->hotspot(o);
    }
    { Fl_Button* o = new Fl_Button(10, 100, 150, 25, "Cancel");
      o->callback((Fl_Callback*)cb_Cancel);
    }
    o->set_modal();
    o->end();
  }
  m_ok = false;
project_name->value( "New Projectname" );
}

void SaveAsDialog::show() {
  saveAsDialog->show();
}

int SaveAsDialog::shown() {
  return saveAsDialog->shown();
}

bool SaveAsDialog::ok() {
  return m_ok;
}

const char* SaveAsDialog::projectName() {
  return project_name->value();
}

SaveAsDialog::~SaveAsDialog() {
  delete saveAsDialog;
}
